name = Default layout
description = layout for all pages.
preview = preview.png
template = default-layout

; Regions
regions[topline]        = Top line
regions[branding]       = Branding
regions[header]         = Header
regions[header_nav]     = Header navigation bar
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/default/default.layout.css
