<?php

/**
 * Implements hook_form_alter().
 */
function wallpapyrus_custom_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'views_exposed_form' && ($form['#id'] == 'views-exposed-form-search-page')) {
    $form['text']['#attributes'] = array('placeholder' => array('Поиск обоев'));
  }
}

/**
 * Implements hook_user_login().
 */
function wallpapyrus_custom_user_login(&$edit, $account) {
  if (!isset($_POST['form_id']) || $_POST['form_id'] != 'user_pass_reset') {
    if(in_array('authenticated user', $account->roles)) {
      $_GET['destination'] = '/';
    }
  }
}
