<?php

/**
 * Implements hook_menu().
 */
function wallpapyrus_downloads_menu() {
  $items['wallpapyrus_downloads/%'] = array(
    'page callback' => 'wallpapyrus_downloads_ajax_callback',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_preprocess_node().
 */
function wallpapyrus_downloads_preprocess_node(&$variables) {
  drupal_add_js(drupal_get_path('module', 'wallpapyrus_downloads') . '/wallpapyrus_downloads.js');
  drupal_add_js(array('nid' => $variables['node']->nid), 'setting');
}

/**
 * Ajax callback: increase downloads counter.
 */
function wallpapyrus_downloads_ajax_callback($nid) {
  $node = node_load($nid);
  $count = $node->field_download_count[LANGUAGE_NONE][0]['value'] + 1;
  $node->field_download_count[LANGUAGE_NONE][0]['value'] = $count;
  node_save($node);

  drupal_json_output($count);
}
